apiVersion: v1
kind: Service
metadata:
  name: t5input-frontend
  namespace: default
spec:
  selector:
    app: t5input-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
